allowBuilds:
  '@firebase/util': false
  '@prisma/engines': false
  '@sentry-internal/node-cpu-profiler': false
  core-js: false
  esbuild: false
  msw: false
  prisma: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
