-- Migration: Add FK on products.category, add missing indexes
-- Generated by architecture improvement pass

-- 1. FK: products.category → product_categories.id
-- Clean up orphaned categories first (set to 'general' if missing)
-- ALTER TABLE products ADD CONSTRAINT products_category_fk
--   FOREIGN KEY (category) REFERENCES product_categories(id);
-- NOTE: Run the UPDATE below first if you have products referencing non-existent categories

-- 2. New indexes on products
CREATE INDEX IF NOT EXISTS "products_category_idx" ON "products" ("category");
CREATE INDEX IF NOT EXISTS "products_current_stock_idx" ON "products" ("current_stock");

-- 3. Composite index on fiado_transactions for customer balance queries
CREATE INDEX IF NOT EXISTS "fiado_transactions_cliente_date_idx" ON "fiado_transactions" ("cliente_id", "date");

-- 4. Indexes on cash_movements for corte reconciliation
CREATE INDEX IF NOT EXISTS "cash_movements_corte_id_idx" ON "cash_movements" ("corte_id");
CREATE INDEX IF NOT EXISTS "cash_movements_tipo_idx" ON "cash_movements" ("tipo");

-- 5. Add FK constraint (run after verifying all categories exist)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'products_category_product_categories_id_fk'
      AND table_name = 'products'
  ) THEN
    ALTER TABLE "products"
      ADD CONSTRAINT "products_category_product_categories_id_fk"
      FOREIGN KEY ("category") REFERENCES "product_categories"("id");
  END IF;
END $$;
